jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      npm install
      npm test
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: |
      npm install
      npm test
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      npm install
      npm test
